import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/shared/sideBar/SideBar";
import InputFeild from "@/components/shared/InputFeild";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid md:grid-cols-8 gap-5">
          <div className="border col-span-2 bg-green-500 p-10">
            <SideBar />
          </div>
          <div className="border col-span-6 min-h-screen bg-red-600 p-10">
            <InputFeild />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
